# -*- coding: utf-8 -*-
"""Dados_Covid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J1BKVtHd-NpFBvtl8Q_nKIrj_9DQCBN4
"""

import pandas as pd
import plotly.express as px
import streamlit as st

#stremalit run Dados_Covid.py

#LENDO O DATASET

df = pd.read_csv('https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv')

#MELHORANDO O NOME DAS COLUNAS DA TABELA

df = df.rename(columns={'newDeaths': 'Novos Óbitos', 'newCases': 'Novos Casos', 'deaths_per_100k_inhabitants': 'Óbitos por 100 Mil Habitantes', 'totalCases_per_100k_inhabitants':'Casos por 100 mil habitantes' })

#SELEÇÃO DO ESTADO 

estados = list(df['state'].unique())
state = st.sidebar.selectbox('Qual o Estado?', estados)


#SELEÇÃO DA COLUNA

colunas = ['Novos Óbitos', 'Novos Casos', 'Óbitos por 100 Mil Habitantes', 'Casos por 100 Mil Habitantes']
column = st.sidebar.selectbox('Qual tipo de Informação?', colunas)

#SELEÇÃO DAS LINHAS QUE PERETENCEM AO ESTADO

df = df[df['state'] == state]

fig = px.line(df, x='date', y=column, title=column + ' - ' + state)
fig.update_layout( xaxis_title='Data', yaxis_title=column.upper(), title = {'x':0.5})

st.title('Dados Covid Brasil')
st.write('Você tem a opção de escolher o Estado e o tipo de informação que desejar')

st.plotly_chart(fig, use_container_width=True)

st.caption('Os dados foram obtidos a partir do site: https:\\github.com/wcota/covid19br')